Repository Someup/backend, pull requests merged in 2024-09, with the labels that each got.

#11 [Deploy] 테스트 서버 배포 설정
  .github/workflows/someup_dev.yml
  Dockerfile
  docker-compose.yml
  src/main/java/project/backend/common/auth/token/TokenProvider.java
  src/main/java/project/backend/common/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#14 [Feature] 카카오 로그인 추가 구현 및 작동 확인
  docker-compose.yml
  src/main/java/project/backend/business/auth/service/AuthService.java
  src/main/java/project/backend/common/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/project/backend/common/auth/jwt/JwtAuthenticationFailEntryPoint.java
  src/main/java/project/backend/common/auth/jwt/JwtFilter.java
  src/main/java/project/backend/common/auth/oauth/KakaoUserDetails.java
  src/main/java/project/backend/common/auth/oauth/KakaoUserDetailsService.java
  src/main/java/project/backend/common/auth/oauth/KakaoUserInfo.java
  src/main/java/project/backend/common/auth/token/RefreshToken.java
  src/main/java/project/backend/common/auth/token/TokenProvider.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/dao/user/entity/User.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
Labels: ✨ Feature, 🌏 Deploy

#16 [Feature] 유저 생성, 유저 정보 조회 기능 구현
  .gitignore
  src/main/java/project/backend/business/auth/service/AuthService.java
  src/main/java/project/backend/business/auth/service/implement/KakaoLoginManager.java
  src/main/java/project/backend/business/auth/service/oauth/KakaoUserDetailsService.java
  src/main/java/project/backend/business/user/service/UserService.java
  src/main/java/project/backend/common/auth/aop/CurrentUserInfo.java
  src/main/java/project/backend/common/auth/jwt/JwtFilter.java
  src/main/java/project/backend/common/auth/oauth/KakaoUserInfo.java
  src/main/java/project/backend/common/auth/token/TokenProvider.java
  src/main/java/project/backend/common/auth/token/TokenResponse.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/common/error/exception/UserNotAuthenticatedException.java
  src/main/java/project/backend/dao/BaseEntity.java
  src/main/java/project/backend/dao/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/project/backend/dao/user/entity/User.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
Labels: ✨ Feature, 🔨 Refactor

#21 [Feature] URL을 통한 게시글 요약 API 구현
  .gitignore
  build.gradle
  src/main/java/project/backend/business/auth/service/AuthService.java
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/post/dto/CreatePostDto.java
  src/main/java/project/backend/business/post/dto/summary/SummaryLanguage.java
  src/main/java/project/backend/business/post/dto/summary/SummaryLevel.java
  src/main/java/project/backend/business/post/dto/summary/SummaryOption.java
  src/main/java/project/backend/business/post/dto/summary/SummaryTone.java
  src/main/java/project/backend/business/post/implement/OpenAIManager.java
  src/main/java/project/backend/business/post/implement/PostManager.java
  src/main/java/project/backend/business/post/implement/PostReader.java
  src/main/java/project/backend/business/post/implement/SummaryAIManager.java
  src/main/java/project/backend/common/auth/jwt/JwtFilter.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/common/error/ErrorCode.java
  src/main/java/project/backend/presentation/post/controller/PostController.java
  src/main/java/project/backend/presentation/post/dto/request/SummaryOptionRequest.java
  src/main/java/project/backend/presentation/post/dto/request/SummaryUrlRequest.java
  src/main/java/project/backend/repository/post/PostRepository.java
  src/main/resources/application.yml
Labels: ✨ Feature

#23 [Feature] 로그아웃 구현
  .github/workflows/someup_dev.yml
  src/main/java/project/backend/business/auth/AuthService.java
  src/main/java/project/backend/business/auth/implement/KakaoLoginManager.java
  src/main/java/project/backend/business/auth/implement/TokenProvider.java
  src/main/java/project/backend/business/auth/oauth/KakaoUserDetailsService.java
  src/main/java/project/backend/business/auth/request/TokenServiceRequest.java
  src/main/java/project/backend/business/auth/response/TokenServiceResponse.java
  src/main/java/project/backend/business/user/UserService.java
  src/main/java/project/backend/common/auth/jwt/JwtFilter.java
  src/main/java/project/backend/common/auth/token/BlacklistToken.java
  src/main/java/project/backend/common/auth/token/RefreshToken.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/common/error/ErrorCode.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
  src/main/java/project/backend/presentation/auth/util/TokenExtractor.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
  src/main/java/project/backend/repository/auth/BlacklistTokenRedisRepository.java
  src/main/java/project/backend/repository/auth/RefreshTokenRedisRepository.java
  src/main/java/project/backend/repository/user/UserRepository.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor, 🌏 Deploy

#27 [Refactor] security 구조 변경
  src/main/java/project/backend/business/auth/AuthService.java
  src/main/java/project/backend/business/auth/implement/KakaoLoginManager.java
  src/main/java/project/backend/business/auth/implement/TokenProvider.java
  src/main/java/project/backend/business/auth/oauth/KakaoUserDetailsService.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/common/error/ErrorCode.java
  src/main/java/project/backend/common/error/ExceptionHandlerFilter.java
  src/main/java/project/backend/entity/token/BlacklistToken.java
  src/main/java/project/backend/entity/token/RefreshToken.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
  src/main/java/project/backend/presentation/post/controller/PostController.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
  src/main/java/project/backend/repository/auth/BlacklistTokenRedisRepository.java
  src/main/java/project/backend/repository/auth/RefreshTokenRedisRepository.java
  src/main/java/project/backend/security/aop/AssignCurrentUserInfo.java
  src/main/java/project/backend/security/aop/AssignCurrentUserInfoAspect.java
  src/main/java/project/backend/security/aop/AssignOrNullCurrentUserInfo.java
  src/main/java/project/backend/security/aop/CurrentUserInfo.java
  src/main/java/project/backend/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/project/backend/security/jwt/JwtAuthenticationFailEntryPoint.java
  src/main/java/project/backend/security/jwt/JwtFilter.java
  src/main/java/project/backend/security/oauth/KakaoUserDetails.java
  src/main/java/project/backend/security/oauth/KakaoUserInfo.java
Labels: 🔨 Refactor

#28 [Feature] 사용자 Request 유효성 검증 추가 및 Request, Response 구조 변경
  src/main/java/project/backend/business/auth/response/TokenServiceResponse.java
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/post/dto/CreatePostDto.java
  src/main/java/project/backend/business/post/dto/PostDetailDto.java
  src/main/java/project/backend/business/post/dto/PostListDto.java
  src/main/java/project/backend/business/post/dto/PostTagDto.java
  src/main/java/project/backend/business/post/implement/PostManager.java
  src/main/java/project/backend/business/post/implement/PostReader.java
  src/main/java/project/backend/business/post/implement/SummaryAIManager.java
  src/main/java/project/backend/business/post/request/CreatePostServiceRequest.java
  src/main/java/project/backend/business/post/request/PostDetailServiceRequest.java
  src/main/java/project/backend/business/post/request/PostListServiceRequest.java
  src/main/java/project/backend/business/post/request/PostTagRequest.java
  src/main/java/project/backend/business/post/request/summary/SummaryLanguage.java
  src/main/java/project/backend/business/post/request/summary/SummaryLevel.java
  src/main/java/project/backend/business/post/request/summary/SummaryOption.java
  src/main/java/project/backend/business/post/request/summary/SummaryTone.java
  src/main/java/project/backend/business/post/response/CreateUpdatePostResponse.java
  src/main/java/project/backend/business/post/response/PostDetailResponse.java
  src/main/java/project/backend/business/post/response/PostListResponse.java
  src/main/java/project/backend/business/tag/implement/TagManager.java
  src/main/java/project/backend/business/tag/implement/TagReader.java
  src/main/java/project/backend/business/user/UserService.java
  src/main/java/project/backend/business/user/implement/UserReader.java
  src/main/java/project/backend/business/user/response/UserResponse.java
  src/main/java/project/backend/entity/user/User.java
  src/main/java/project/backend/presentation/auth/util/TokenExtractor.java
  src/main/java/project/backend/presentation/post/controller/PostController.java
  src/main/java/project/backend/presentation/post/dto/request/SummaryOptionRequest.java
  src/main/java/project/backend/presentation/post/dto/request/SummaryUrlRequest.java
  src/main/java/project/backend/presentation/post/dto/request/UpdatePostRequest.java
  src/main/java/project/backend/presentation/post/dto/response/CreateUpdatePostResponse.java
  src/main/java/project/backend/presentation/post/dto/response/PostDetailResponse.java
  src/main/java/project/backend/presentation/post/dto/response/PostListResponse.java
  src/main/java/project/backend/presentation/post/request/SummaryOptionRequest.java
  src/main/java/project/backend/presentation/post/request/SummaryUrlRequest.java
  src/main/java/project/backend/presentation/post/request/UpdatePostRequest.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
Labels: ✨ Feature, 🔨 Refactor

#30 [Refactor] 토큰, 리이슈, 로그아웃 로직 변경
  src/main/java/project/backend/business/auth/AuthService.java
  src/main/java/project/backend/common/config/RedisConfig.java
  src/main/java/project/backend/common/error/ErrorCode.java
  src/main/java/project/backend/entity/token/RefreshToken.java
  src/main/java/project/backend/presentation/auth/util/TokenExtractor.java
  src/main/java/project/backend/repository/auth/BlacklistTokenRedisRepository.java
  src/main/java/project/backend/repository/auth/RefreshTokenRedisRepository.java
Labels: 🔨 Refactor

#31 [Chore] 게시글 관련 API 고도화
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/post/implement/PostManager.java
  src/main/java/project/backend/business/post/implement/PostReader.java
  src/main/java/project/backend/business/post/implement/SummaryAIManager.java
  src/main/java/project/backend/business/post/request/PostDetailServiceRequest.java
  src/main/java/project/backend/business/post/request/PostListServiceRequest.java
  src/main/java/project/backend/business/post/request/summary/SummaryLanguage.java
  src/main/java/project/backend/business/post/request/summary/SummaryLevel.java
  src/main/java/project/backend/business/post/request/summary/SummaryOption.java
  src/main/java/project/backend/business/post/request/summary/SummaryTone.java
  src/main/java/project/backend/business/post/response/PostDetailDto.java
  src/main/java/project/backend/business/post/response/PostDetailResponse.java
  src/main/java/project/backend/business/post/response/PostListDto.java
  src/main/java/project/backend/business/post/response/PostListResponse.java
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/presentation/post/controller/PostController.java
  src/main/java/project/backend/presentation/post/request/SummaryOptionRequest.java
  src/main/java/project/backend/presentation/post/request/SummaryUrlRequest.java
  src/main/java/project/backend/presentation/post/request/UpdatePostRequest.java
  src/main/java/project/backend/repository/post/PostRepository.java
  src/main/java/project/backend/repository/post/PostSpecification.java
  src/main/java/project/backend/repository/tag/TagRepository.java
Labels: ✨ Feature

#34 [Refactor] 토큰 관리 방식 변경
  src/main/java/project/backend/business/auth/AuthService.java
  src/main/java/project/backend/business/auth/implement/TokenProvider.java
  src/main/java/project/backend/business/auth/response/TokenServiceResponse.java
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/user/UserService.java
  src/main/java/project/backend/business/user/implement/UserReader.java
  src/main/java/project/backend/business/user/response/UserInfoResponse.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
  src/main/java/project/backend/presentation/auth/util/TokenCookieManager.java
  src/main/java/project/backend/presentation/auth/util/TokenExtractor.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
  src/main/java/project/backend/security/aop/AssignCurrentUserInfoAspect.java
Labels: 🔨 Refactor

#37 [Refactor] Cookie SameSite 관리
  src/main/java/project/backend/presentation/auth/util/TokenCookieManager.java
Labels: 🔨 Refactor
