Repository Someup/backend, pull requests merged in 2024-10, with the labels that each got.

#35 [Feature] Swagger 추가하기
  build.gradle
  src/main/java/project/backend/common/config/SecurityConfig.java
  src/main/java/project/backend/common/config/SwaggerConfig.java
  src/main/java/project/backend/presentation/auth/controller/AuthController.java
  src/main/java/project/backend/presentation/auth/controller/AuthControllerDocs.java
  src/main/java/project/backend/presentation/post/controller/PostController.java
  src/main/java/project/backend/presentation/post/controller/PostControllerDocs.java
  src/main/java/project/backend/presentation/user/controller/UserController.java
  src/main/java/project/backend/presentation/user/controller/UserControllerDocs.java
  src/main/java/project/backend/security/aop/AssignCurrentUserInfoAspect.java
  src/main/java/project/backend/security/jwt/JwtFilter.java
  src/main/resources/application.yml
Labels: ✨ Feature

#40 [Feature] 메모 기능 추가
  .gitignore
  src/main/java/project/backend/business/memo/MemoService.java
  src/main/java/project/backend/business/memo/implement/MemoManager.java
  src/main/java/project/backend/business/memo/request/CreateUpdateMemoServiceRequest.java
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/post/implement/PostReader.java
  src/main/java/project/backend/presentation/memo/controller/MemoController.java
  src/main/java/project/backend/presentation/memo/controller/MemoControllerDocs.java
  src/main/java/project/backend/presentation/memo/request/CreateUpdateMemoRequest.java
  src/main/resources/application.yml
Labels: ✨ Feature

#43 [Feature] 게시물 아카이브 대응 및 리팩토링
  build.gradle
  src/main/java/project/backend/business/memo/implement/MemoManager.java
  src/main/java/project/backend/business/post/PostService.java
  src/main/java/project/backend/business/post/implement/PostManager.java
  src/main/java/project/backend/business/post/implement/PostReader.java
  src/main/java/project/backend/business/post/implement/SummaryAIManager.java
  src/main/java/project/backend/business/post/implement/SummaryManager.java
  src/main/java/project/backend/business/post/request/PostListServiceRequest.java
  src/main/java/project/backend/business/post/request/UpdatePostServiceRequest.java
  src/main/java/project/backend/business/post/response/CreateUpdatePostResponse.java
  src/main/java/project/backend/business/post/response/PostCountResponse.java
  src/main/java/project/backend/business/post/response/PostDetailResponse.java
  src/main/java/project/backend/business/post/response/PostListResponse.java
  src/main/java/project/backend/business/post/response/dto/SummaryResultDto.java
  src/main/java/project/backend/business/post/util/DateTimeManager.java
  src/main/java/project/backend/business/post/util/JsonParser.java
  src/main/java/project/backend/business/user/implement/UserReader.java
  src/main/java/project/backend/common/config/SwaggerConfig.java
  src/main/java/project/backend/common/error/ErrorCode.java
  src/main/java/project/backend/entity/post/Post.java
  src/main/java/project/backend/presentation/memo/MemoController.java
  src/main/java/project/backend/presentation/post/PostController.java
  src/main/java/project/backend/presentation/post/docs/PostControllerDocs.java
  src/main/java/project/backend/presentation/post/request/UpdatePostRequest.java
  src/main/java/project/backend/repository/post/PostRepository.java
  src/main/java/project/backend/repository/post/PostSpecification.java
  src/main/resources/application.yml
Labels: ✨ Feature

#55 [Feature] 회원탈퇴 구현
  src/main/java/project/backend/business/auth/AuthService.java
  src/main/java/project/backend/business/auth/implement/KakaoLoginManager.java
  src/main/java/project/backend/business/auth/oauth/KakaoUserDetailsService.java
  src/main/java/project/backend/business/user/implement/UserManager.java
  src/main/java/project/backend/entity/user/User.java
  src/main/java/project/backend/presentation/archive/request/CreateUpdateArchiveRequest.java
  src/main/java/project/backend/presentation/auth/AuthController.java
  src/main/java/project/backend/repository/user/UserRepository.java
  src/main/java/project/backend/security/aop/AssignCurrentUserInfoAspect.java
  src/main/java/project/backend/security/jwt/JwtFilter.java
Labels: ✨ Feature

#57 [Fix] 게시물 관련 QA
  src/main/java/project/backend/business/archive/implement/ArchiveReader.java
  src/main/java/project/backend/business/post/implement/PostManager.java
  src/main/java/project/backend/business/post/implement/SummaryManager.java
Labels: 🐞 BugFix

#59 [Refactor] 유효성 검사 정책 수정 반영
  build.gradle
  docker-compose.yml
  src/main/java/project/backend/BackendApplication.java
  src/main/java/project/backend/business/archive/implement/ArchiveManager.java
  src/main/java/project/backend/presentation/archive/request/CreateUpdateArchiveRequest.java
  src/main/java/project/backend/presentation/post/request/SummaryUrlRequest.java
  src/main/java/project/backend/presentation/post/request/UpdatePostRequest.java
  src/main/java/project/backend/repository/archive/ArchiveRepository.java
Labels: 🔨 Refactor
